<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DAFTAR</name>
   <tag></tag>
   <elementGuidId>79cb3aa6-2a96-4b23-bf3f-881072c0c83a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@type='submit'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.next-first</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4fa4d4b0-95db-4d77-9bbf-14f2ee17e5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6de439d7-47bc-4e5d-8f69-5370b8fc5eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary next-first</value>
      <webElementGuid>dcc65221-102a-452c-b679-ff4f0c185548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    DAFTAR
                </value>
      <webElementGuid>25d666b8-d14b-42da-8556-c2327683dec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerTalent&quot;)/div[@class=&quot;modal-dialog modal-dialog-scrollable minht boxIn&quot;]/div[@class=&quot;modal-content loadRegTalent&quot;]/div[@class=&quot;row inr&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;wrap-inquiry&quot;]/div[1]/a[@class=&quot;btn btn-primary next-first&quot;]</value>
      <webElementGuid>6516dea0-0561-4292-9bc7-4ea3cb8a7d89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@type='submit'])[3]</value>
      <webElementGuid>66968ab4-e764-478c-9240-1e29967212bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registerTalent']/div/div/div/div/div/div/a[4]</value>
      <webElementGuid>5fb2edfb-6a1f-4660-9c25-0397638b5f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DAFTAR')]</value>
      <webElementGuid>0dedf7cf-5d80-4a6f-bda9-630081f9d50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan Daftar'])[1]/following::a[1]</value>
      <webElementGuid>b49a9d13-61dd-4111-9478-ca0297c7315a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[3]/following::a[2]</value>
      <webElementGuid>f9817c51-d729-447b-9d74-9af9bb1c21ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Pendaftaran Sudah Dicek'])[1]/preceding::a[1]</value>
      <webElementGuid>1b7e2cca-4417-4f33-8a60-d79bb5626b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Form Pendaftaran?'])[1]/preceding::a[2]</value>
      <webElementGuid>13ea3b7a-56f0-4cd0-9c02-91176d4d4506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAFTAR']/parent::*</value>
      <webElementGuid>2dbd64d8-1670-437f-ad30-4e5be40b1f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>b847f189-98c0-4afd-80da-4f3843a7bce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'submit' and (text() = '
                    DAFTAR
                ' or . = '
                    DAFTAR
                ')]</value>
      <webElementGuid>3a75b023-80e5-46fd-8158-ddc8917af579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
