<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dari mana kamu dapat informasi soal k_9ca1e3</name>
   <tag></tag>
   <elementGuidId>ce984010-37e7-44c1-a0c9-804a12019842</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refrensi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#refrensi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eec39954-0c58-4048-afd2-4e34cbb0200b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5006600-993c-4b65-8e99-9cdd845ea5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>options</value>
      <webElementGuid>294cd7b8-d77a-4b59-a4b3-9c6aa667b045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refrensi</value>
      <webElementGuid>e357fc52-0408-4591-83e5-a42097b1fada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select w-25</value>
      <webElementGuid>15162c53-b548-42e0-9d88-4d7edec72dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select or enter an option</value>
      <webElementGuid>89cdc29e-adf6-4a75-bf9c-70baa0b9a518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refrensi</value>
      <webElementGuid>c2fba296-5529-41cc-897e-1fd2dc39c840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refrensi&quot;)</value>
      <webElementGuid>235849ee-87c0-4946-bd76-5b792cc2b26d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refrensi']</value>
      <webElementGuid>571c8911-d746-483b-99d8-3cee59b51aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register_main']/div[6]/div/div[2]/div/input</value>
      <webElementGuid>218fd796-2f4c-4f65-aa8a-531e9f9e8ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/input</value>
      <webElementGuid>3b2ca9d0-3254-493f-93f2-1f52199d6d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'refrensi' and @placeholder = 'Select or enter an option' and @name = 'refrensi']</value>
      <webElementGuid>51206f45-4d8a-498e-b5fa-f4fb54590d74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
