<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DAFTAR</name>
   <tag></tag>
   <elementGuidId>7721486b-e7d5-47a3-ace0-41f39c5cb4de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@type='submit'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.next-first</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>43ff9e26-3b6b-4ab5-af9f-363236e9a9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1c89ed3e-8eb4-4172-af86-0e18f9c67eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary next-first</value>
      <webElementGuid>2f559af8-c86c-4a60-ae91-f6c5eedf7fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    DAFTAR
                </value>
      <webElementGuid>2fee0907-4906-46ad-8e2f-938ade576aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerTalent&quot;)/div[@class=&quot;modal-dialog modal-dialog-scrollable minht boxIn&quot;]/div[@class=&quot;modal-content loadRegTalent&quot;]/div[@class=&quot;row inr&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;wrap-inquiry&quot;]/div[1]/a[@class=&quot;btn btn-primary next-first&quot;]</value>
      <webElementGuid>8d5b2255-8604-4f5d-a5c7-4bb8b3c9252e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@type='submit'])[3]</value>
      <webElementGuid>d6888c34-1cb1-4ae6-80ef-62f50be5305c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registerTalent']/div/div/div/div/div/div/a[4]</value>
      <webElementGuid>24135528-5fde-41ef-99af-d9a84f7c1b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DAFTAR')]</value>
      <webElementGuid>d785bf9e-616d-4de5-ba58-0c81a542b58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan Daftar'])[1]/following::a[1]</value>
      <webElementGuid>e0f49926-5bc0-4e27-9421-080fc8b5a6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[3]/following::a[2]</value>
      <webElementGuid>3d47dc79-093f-4b7e-b8cd-a392a716da53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Pendaftaran Sudah Dicek'])[1]/preceding::a[1]</value>
      <webElementGuid>fae66328-c402-4cd5-9c1d-ce10eea5c142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Form Pendaftaran?'])[1]/preceding::a[2]</value>
      <webElementGuid>c96d9ae4-58b1-4ae4-a395-3076460e12b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAFTAR']/parent::*</value>
      <webElementGuid>0efb9ce3-ec99-4788-9f5c-c2493d78dd04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>72da3303-6bae-4cf0-a9da-44f76438bd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'submit' and (text() = '
                    DAFTAR
                ' or . = '
                    DAFTAR
                ')]</value>
      <webElementGuid>00283539-53be-42c5-810d-ea0b34da0fa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
