<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>01b533e5-95d8-43f8-a2c9-14a0b9966158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;$('.info').hide()&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-border.btn-login.btn-xs.light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bac1759e-625b-40c0-937b-74de338cbcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-border btn-login btn-xs light</value>
      <webElementGuid>0b0817f1-0a57-4442-a442-4487b519b844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#ModalLogin</value>
      <webElementGuid>2467bdf2-fca9-4264-a26c-bc1fa8f78d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>e07daacf-37f6-493e-84a5-de549b6f09c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('.info').hide()</value>
      <webElementGuid>a57ba8ad-f054-4ba8-bfe0-c4a110b75895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>cfe52c6c-d0f0-46b6-a00d-66532a07a39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;menu-classic menu-fixed menu-one-page align-right menu-transparent light&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;menu-cnt&quot;]/div[@class=&quot;menu-right&quot;]/div[@class=&quot;menu-custom-area&quot;]/a[@class=&quot;btn btn-border btn-login btn-xs light&quot;]</value>
      <webElementGuid>fd4a9bae-0f5a-417f-bb4d-49389d46a0ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;$('.info').hide()&quot;]</value>
      <webElementGuid>b24be57b-fc79-4bcd-9433-1153ea9ca512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>25ee114e-45e0-4f29-ad21-1da0f02951b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::a[1]</value>
      <webElementGuid>1a7ca711-6df3-44a0-9541-898047112c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/following::a[2]</value>
      <webElementGuid>8278a4e6-b2d1-4758-b043-709c4cb818d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::a[2]</value>
      <webElementGuid>580aaefe-6d90-4ab9-9af0-cf1ab90bb5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>c6878914-fc1f-4072-8a99-62ecfe6272f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>da3614fc-31eb-4a19-916e-8412e309d8a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
