<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DAFTAR</name>
   <tag></tag>
   <elementGuidId>136856a1-9f6d-48ff-ab1d-00397e59ef8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@type='submit'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.next-first</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c82987e-b6b9-4285-8cca-0d143ed211de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a20c79c4-8f9a-4df2-9a1c-feea9a6b8fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary next-first</value>
      <webElementGuid>024d6b83-50d6-436b-b591-9c3d3ac6e23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    DAFTAR
                </value>
      <webElementGuid>d2f13461-541d-4b68-9be9-35356a9d3ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerTalent&quot;)/div[@class=&quot;modal-dialog modal-dialog-scrollable minht boxIn&quot;]/div[@class=&quot;modal-content loadRegTalent&quot;]/div[@class=&quot;row inr&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;wrap-inquiry&quot;]/div[1]/a[@class=&quot;btn btn-primary next-first&quot;]</value>
      <webElementGuid>06af5461-ba92-40b7-b426-2796283f5c51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@type='submit'])[3]</value>
      <webElementGuid>692a36fe-88b8-4ef1-921e-5bbcfa4e4592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registerTalent']/div/div/div/div/div/div/a[4]</value>
      <webElementGuid>6432d346-f319-4a31-be97-268723bdcdc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DAFTAR')]</value>
      <webElementGuid>916043a4-df53-4fbf-871b-ff9fa022abc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan Daftar'])[1]/following::a[1]</value>
      <webElementGuid>ddc8236c-f5e1-44b3-8b4e-15ccf75dfde9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[3]/following::a[2]</value>
      <webElementGuid>12d343fa-ab2b-4970-af1a-97a04f03625b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Pendaftaran Sudah Dicek'])[1]/preceding::a[1]</value>
      <webElementGuid>88e85180-06d2-4fe0-abf7-bdd69d4aff9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Form Pendaftaran?'])[1]/preceding::a[2]</value>
      <webElementGuid>80011a13-3ef3-4b2d-8d2f-4ff6d7120dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAFTAR']/parent::*</value>
      <webElementGuid>060b5275-dd76-4b8e-ab54-8182704f1a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>d5aee820-6099-4840-85f0-451ca205c696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'submit' and (text() = '
                    DAFTAR
                ' or . = '
                    DAFTAR
                ')]</value>
      <webElementGuid>d6b94dd2-0c16-4a0d-b5c5-ee70d9d33f23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
