<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Email_email</name>
   <tag></tag>
   <elementGuidId>de431eda-5da8-4165-b831-95a21fa34876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Email'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#register_main > div.form-group > div.row > div.col-md-8 > #Email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8de83921-f176-4d4f-ba48-37fcadfdb3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f3e7aea5-3322-4eea-8b8e-952772aa5307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>faeda86a-3605-4bb4-99a1-65228a8b33c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>22d62197-ec0b-477f-a270-e0a3c0f1c8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>4bf30676-8c98-43aa-b850-8b06349f6f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your Email</value>
      <webElementGuid>02799a31-1df2-4429-8f90-1523d2bc8c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register_main&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/input[@id=&quot;Email&quot;]</value>
      <webElementGuid>e7a9bd6b-c5ac-4d7e-acfc-db5032e39b3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Email'])[2]</value>
      <webElementGuid>bd76094c-fbab-4315-a325-31b82853bbf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register_main']/div[2]/div/div[2]/input</value>
      <webElementGuid>17c29b3c-39c9-4ef5-b4c3-714b5ef6d60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/form/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>698cb0f8-ace8-4270-a68c-e8d242468a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @id = 'Email' and @placeholder = 'Your Email']</value>
      <webElementGuid>7f69af8d-0e97-483a-9960-03ab6b5a7c9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
