<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dari mana kamu dapat informasi soal k_9ca1e3</name>
   <tag></tag>
   <elementGuidId>a0b949c7-6115-446e-a761-1309634efad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refrensi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#refrensi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9040fa24-094c-490e-adc8-3b7ab7d15d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>524f27fe-57b9-46fc-b266-4051d34830b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>options</value>
      <webElementGuid>18784155-8363-40be-af93-753556b77a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refrensi</value>
      <webElementGuid>59cf08b4-13bf-4107-aed2-98db7effcec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select w-25</value>
      <webElementGuid>6def6e84-fb91-4257-afa3-257044f04bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select or enter an option</value>
      <webElementGuid>57ac41cb-424c-4833-b8df-55621566c51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refrensi</value>
      <webElementGuid>c078d0a9-78cc-4288-9fa1-fc18baa717f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refrensi&quot;)</value>
      <webElementGuid>6359d592-71b6-46c0-8951-169cb1b6a58f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refrensi']</value>
      <webElementGuid>4f1a078e-84eb-4c7e-b0f6-0aa369345121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register_main']/div[6]/div/div[2]/div/input</value>
      <webElementGuid>a1239e21-67f8-4db7-8a01-23324769aa89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/input</value>
      <webElementGuid>2c7f9ac3-a2d1-44f3-826f-3257954fce6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'refrensi' and @placeholder = 'Select or enter an option' and @name = 'refrensi']</value>
      <webElementGuid>4f035441-2dfc-4581-a41e-7edb90bbcf8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
